---
title: "10xgenomicsdata"
output: word_document
---

```{r}
library(dplyr)
library(tidyr)
```

```{r}
data = read.csv ('/home/sedreh/university_files/ITMO/semester2/Bcellsproject/fifth_session/Human_dataset/human_data.csv')
filtered_data = read.csv ('/home/sedreh/university_files/ITMO/semester2/Bcellsproject/fifth_session/Human_dataset/human_filtered_data.csv')
```

```{r}
#Number of cells (As we have several copies of each barcode,we need to count just one copy of unique barcoe)

barcode_summary <- function(data)
{
  number_of_cells <- data %>% 
    distinct(barcode) %>% 
    count()
  number_of_cells$n 
}
barcode_summary(data)
barcode_summary(filtered_data)
```

```{r}
#look at to the quality of chains

count_table <- function(data)
{
v_gene_and_j_gene <- filter(data, v_gene != 'None' & j_gene != 'None')
v_gene_and_j_gene <- count(v_gene_and_j_gene)$n

no_v_gene_and_no_j_gene <- filter(data, v_gene == 'None' & j_gene == 'None')
no_v_gene_and_no_j_gene <- count(no_v_gene_and_no_j_gene)$n

v_gene_or_j_gene <- filter(data, v_gene != 'None' | j_gene != 'None')
v_gene_or_j_gene <- count(v_gene_or_j_gene)$n

stats <- data.frame(v_gene_and_j_gene, v_gene_or_j_gene, no_v_gene_and_no_j_gene)
stats
}
count_table(data)
count_table(filtered_data)
```

```{r}
#How many IGK,IGH, IGL and Multi we have in the data?
Summary <- function(data)
{
  chain_summary <- group_by(data, chain)
  chain_summary <- summarize(chain_summary, count=n()) 
  chain_summary
}
Summary (data)
Summary (filtered_data)
```

```{r}
#Number of copies of each cell

barcode_summary <- function(data)
  {
  barcode_summary <- group_by(data, barcode) 
  barcode_summary <- summarize(barcode_summary, count=n())
  barcode_summary
}
barcode_summary(data)
barcode_summary(filtered_data)
```

```{r}
#show the number of occurance of each copy

barcode_summary <- function(data)
  {
  barcode_summary <- group_by(data, barcode) 
  barcode_summary <- summarize(barcode_summary, count=n())
  barcode_summary <- group_by(barcode_summary, count) 
  #barcode_summary <- summarize(barcode_summary, count_total=n())
  barcode_summary
}
result_row <- barcode_summary(data)
result_row

```

```{r}
barcode_summary <- function(filtered_data)
  {
  barcode_summary <- group_by(filtered_data, barcode) 
  barcode_summary <- summarize(barcode_summary, count=n())
  barcode_summary <- group_by(barcode_summary, count) 
  #barcode_summary <- summarize(barcode_summary, count_total=n())
  barcode_summary
}
result_filtered <- barcode_summary(filtered_data)
result_filtered
```

```{r}
par(mfrow = c(1,2))
hist(result_row$count, xlim=c(1,12),ylim=c(0,8000), xlab="chain", ylab="count", col="skyblue")
hist(result_filtered$count, xlim=c(1,12),ylim=c(0,8000), xlab="chain", ylab="count", col="green")
```

```{r}
#counts number of occurance of each chain type for every unique barcodehow 

occurance_of_each_chain <- function(data)
{
  result_data <- data %>%
    group_by(barcode, chain) %>%
    filter(chain %in% c('IGK','IGH','IGL')) %>%
    summarize(count=n())
  result_data
}
occurance_of_each_chain(data)
```

```{r}
# I have all conditions here

occurance_of_each_chain <- function(data)
  {
  result <- data %>%
    group_by(barcode, chain) %>%
    filter(chain %in% c('IGK','IGH','IGL')) %>%
    summarize(count=n())
  result <- unite(result, 'result_chain', count, chain, remove=F, sep='') 
  result <- summarize(result, type=paste(result_chain, collapse='_'), count=sum(count))
  result
}
occurance_of_each_chain(data)
```

```{r}
# I have all conditions here for filtered data

occurance_of_each_chain <- function(filtered_data)
  {
  result <- filtered_data %>%
    group_by(barcode, chain) %>%
    filter(chain %in% c('IGK','IGH','IGL')) %>%
    summarize(count=n())
  result <- unite(result, 'result_chain', count, chain, remove=F, sep='') 
  result <- summarize(result, type=paste(result_chain, collapse='_'), count=sum(count))
  result
}
occurance_of_each_chain(filtered_data)
```

```{r}
# I added whichever condition that I want from data

Condition <- function (result)
  {
  
  many_conditions = c(
  '1IGL', '1IGH', '1IGK', '1IGH_1IGK_1IGL' , '1IGH_1IGL' , '1IGH_1IGK', '1IGH_2IGK', 'IGH_2IGL')
  result %>% 
  filter(type %in% many_conditions) %>% 
  group_by(type) %>% 
  summarise(total=n())
}
Condition(occurance_of_each_chain(data))
```

```{r}
# I added whichever condition that I want from data

Condition <- function (result)
  {
  
  many_conditions = c(
  '1IGL', '1IGH', '1IGK', '1IGH_1IGK_1IGL' , '1IGH_1IGL' , '1IGH_1IGK', '1IGH_2IGK', 'IGH_2IGL')
  result %>% 
  filter(type %in% many_conditions) %>% 
  group_by(type) %>% 
  summarise(total=n())
}
Condition(occurance_of_each_chain(filtered_data))
```

