---
title: "Final_work"
output: word_document
---
```{r}
library(tidyr)
library(dplyr)
library(data.table)
```

```{r}
data <-read.csv('/home/sedreh/Mouse_migmapresult.csv', header = T, sep = '\t')
data
```

```{r}
preprocess_data <- function(data) {
separate(data,
         col = "read.header",
         into = c("read", "header"),
         sep = "_")  %>% 
    rename(
    barcode = read,
    v_gene= v.segment,
    d_gene = d.segment,
    j_gene= j.segment
    ) %>%
    select(barcode, v_gene, d_gene, j_gene, no.stop, in.frame) %>%
    mutate(
      productive = ifelse(no.stop == "true" & in.frame == "true", T , F)
    )
}
preprocessed_data <- preprocess_data(data)
preprocessed_data
table(preprocessed_data$productive)
```

```{r}
matrix_gene_data <- as.matrix(preprocessed_data[,2:4])
 matrix_gene_data <- substr(matrix_gene_data, 1, 3) # get only first three characters
 preprocessed_data$chain <- apply(matrix_gene_data, 1, function(x) {
   x <- x[!(x %in% ".")] # removeing . 
   x <- unique(x) # get unique value from row
   if(length(x) == 0) { # if all are . then return none
     "None"
   } else if (length(x) > 1) { # if more than 1 unique value then it's multi
     "Multi"
   } else { # otherwise just single chain value
     x
   }
 })
preprocessed_data
```

```{r}
occurance_of_each_chain <- function(preprocessed_data)
  {
  result <- preprocessed_data %>%
    group_by(barcode, chain) %>%
    filter(chain %in% c('IGK','IGH','IGL')) %>%
    summarize(count=n())
  result <- unite(result, 'result_chain', count, chain, remove=F, sep='') 
  result <- summarize(result, type=paste(result_chain, collapse='_'), count=sum(count))
  result
}
occurance_of_each_chain(preprocessed_data)
```

```{r}
# I added whichever condition that I want from data

Condition <- function (result)
  {
  
  many_conditions = c(
  '1IGH_1IGK_1IGL' , '1IGH_1IGL' , '1IGH_1IGK', '1IGH_2IGK', 'IGH_2IGL')
  result %>% 
  filter(type %in% many_conditions) %>% 
  group_by(type) %>% 
  summarise(total=n())
}
Condition(occurance_of_each_chain(preprocessed_data))
```

```{r}
#counting distance of 2 string
#dist.dna.Tamura("AAACCTGAGACCACGA", "AAACCTGAGCGTAATA", variance = FALSE, GCcontent = NULL)

```


